"""
Store Stock Assistant API
=======================================================
FastAPI service wrapping the trained XGBoost demand-forecasting model and
restock-alert logic, for integration into the company website.

Run locally:
    uvicorn api.main:app --reload --port 8000

Interactive docs (auto-generated by FastAPI) once running:
    http://localhost:8000/docs        (Swagger UI)
    http://localhost:8000/redoc       (ReDoc)

Expects trained model artifacts in ./artifacts/ (produced by src/train_model.py):
  - xgb_demand_model.json
  - label_encoders.pkl
  - feature_cols.json
  - metrics.json
  - feature_importance.csv
  - historical_engineered.parquet
"""

import io
import os
import json
import secrets
import logging
import joblib
import pandas as pd
import numpy as np
from functools import lru_cache
from fastapi import FastAPI, UploadFile, File, HTTPException, Query, Security, Depends
from fastapi.security import APIKeyHeader
from fastapi.middleware.cors import CORSMiddleware

from src.inference_utils import (
    engineer_features, encode_with_saved_encoders, bootstrap_history,
    predict_demand, generate_alerts, GROUP_COLS, DATE_COL,
)
from api.schemas import (
    SalesRecord, ForecastSettings, ItemForecast, ForecastResponse,
    ModelInfo, SchemaResponse, ForecastRecordsRequest,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("store_stock_api")

ARTIFACT_DIR = os.environ.get("ARTIFACT_DIR", "artifacts")

# -----------------------------------------------------------------------
# API KEY AUTH (per-client keys)
# -----------------------------------------------------------------------
# Client keys live in api/api_keys.json (gitignored -- never commit real
# secrets). Format: {"client-name": "secret-key", ...}. Each client gets its
# own key, so access can be revoked for one client (delete its entry, restart
# the server) without breaking any other client.
#
# First-time setup:
#   1. Copy api/api_keys.json.example to api/api_keys.json
#   2. Replace the placeholder values with real random secrets
#   3. Give each client (e.g. the website, an internal tool) its own entry
#
# The API refuses to start if this file is missing or empty -- intentional,
# so it's impossible to accidentally run the API with no authentication.
API_KEYS_PATH = os.environ.get("STORE_STOCK_API_KEYS_PATH", os.path.join(os.path.dirname(__file__), "api_keys.json"))
API_KEYS_JSON_ENV = os.environ.get("STORE_STOCK_API_KEYS_JSON")  # e.g. '{"website": "secret123"}'


def _load_api_keys() -> dict:
    # Prefer an env var (used on hosting platforms like Render, where committing
    # a keys file isn't desired) -- falls back to the local file for local dev.
    if API_KEYS_JSON_ENV:
        try:
            keys = json.loads(API_KEYS_JSON_ENV)
        except json.JSONDecodeError as e:
            raise RuntimeError(f"STORE_STOCK_API_KEYS_JSON env var is not valid JSON: {e}")
    elif os.path.exists(API_KEYS_PATH):
        with open(API_KEYS_PATH) as f:
            try:
                keys = json.load(f)
            except json.JSONDecodeError as e:
                raise RuntimeError(f"API keys file at {API_KEYS_PATH} is not valid JSON: {e}")
    else:
        raise RuntimeError(
            "No API keys found. Either set the STORE_STOCK_API_KEYS_JSON environment "
            "variable, or create api/api_keys.json locally (copy api_keys.json.example)."
        )
    if not keys or not isinstance(keys, dict):
        raise RuntimeError("API keys are empty or malformed. Expected: {\"client-name\": \"secret-key\", ...}")
    return keys


API_KEYS = _load_api_keys()
_KEY_TO_CLIENT = {v: k for k, v in API_KEYS.items()}  # reverse lookup: key -> client_name

_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


def require_api_key(provided_key: str = Security(_api_key_header)) -> str:
    """Dependency that protects an endpoint behind a per-client API key.
    Returns the calling client's name (from api_keys.json) on success, so
    endpoints/logs can identify who made the request. Uses constant-time
    comparison against every known key to avoid leaking which key (if any)
    was close to correct via timing."""
    if provided_key:
        for known_key, client_name in _KEY_TO_CLIENT.items():
            if secrets.compare_digest(provided_key, known_key):
                return client_name
    raise HTTPException(
        status_code=401,
        detail="Missing or invalid API key. Send it in the 'X-API-Key' header.",
    )


REQUIRED_COLUMNS = [
    "Date", "Store ID", "Product ID", "Category", "Region",
    "Inventory Level", "Units Sold", "Units Ordered", "Price", "Discount",
    "Weather Condition", "Promotion", "Competitor Pricing", "Seasonality", "Epidemic",
]

app = FastAPI(
    title="Store Stock Assistant API",
    description=(
        "Forecasts daily demand per store-item and returns restock alerts "
        "(what to order, how much, how urgently) based on uploaded sales data.\n\n"
        "**Authentication**: all endpoints except `/health` and `/schema` require "
        "an API key sent in the `X-API-Key` header."
    ),
    version="1.0.0",
)

# Allow the company website's frontend to call this API from the browser.
# Tighten allow_origins to the actual website domain(s) before going to production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -----------------------------------------------------------------------
# ARTIFACT LOADING (cached once per process, not per-request)
# -----------------------------------------------------------------------
@lru_cache(maxsize=1)
def get_model():
    import xgboost as xgb
    path = xgb.XGBRegressor()
    path.load_model(os.path.join(ARTIFACT_DIR, "xgb_demand_model.json"))
    if not os.path.exists(path):
        raise RuntimeError(f"Model artifact not found at {path}")
    return joblib.load(path)


@lru_cache(maxsize=1)
def get_encoders():
    return joblib.load(os.path.join(ARTIFACT_DIR, "label_encoders.pkl"))


@lru_cache(maxsize=1)
def get_feature_cols():
    with open(os.path.join(ARTIFACT_DIR, "feature_cols.json")) as f:
        return json.load(f)


@lru_cache(maxsize=1)
def get_metrics():
    path = os.path.join(ARTIFACT_DIR, "metrics.json")
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}


@lru_cache(maxsize=1)
def get_feature_importance():
    path = os.path.join(ARTIFACT_DIR, "feature_importance.csv")
    if os.path.exists(path):
        return pd.read_csv(path).head(10).to_dict(orient="records")
    return None


@lru_cache(maxsize=1)
def get_historical():
    path = os.path.join(ARTIFACT_DIR, "historical_engineered.parquet")
    if os.path.exists(path):
        return pd.read_parquet(path)
    return None


def get_trend_direction(demand_trend, threshold: float = 1.0) -> str:
    if pd.isna(demand_trend):
        return "flat"
    if demand_trend > threshold:
        return "up"
    if demand_trend < -threshold:
        return "down"
    return "flat"


def run_full_pipeline(raw_df: pd.DataFrame) -> pd.DataFrame:
    """Shared pipeline: bootstrap history -> engineer features -> encode -> predict.
    Same logic the Streamlit app used, now reused by the API."""
    model = get_model()
    encoders = get_encoders()
    feature_cols = get_feature_cols()
    historical_df = get_historical()

    if historical_df is not None:
        combined_raw = bootstrap_history(raw_df, historical_df)
    else:
        combined_raw = raw_df.copy()

    engineered = engineer_features(combined_raw)
    encoded = encode_with_saved_encoders(engineered, encoders)
    preds = predict_demand(model, encoded, feature_cols)
    encoded["Predicted_Demand"] = preds

    upload_keys = raw_df[GROUP_COLS + [DATE_COL]].copy()
    upload_keys[DATE_COL] = pd.to_datetime(upload_keys[DATE_COL])
    encoded[DATE_COL] = pd.to_datetime(encoded[DATE_COL])
    result = encoded.merge(upload_keys, on=GROUP_COLS + [DATE_COL], how="inner")
    return result


def build_item_forecasts(alerts_df: pd.DataFrame) -> list:
    items = []
    for _, row in alerts_df.iterrows():
        trend_dir = get_trend_direction(row.get("demand_trend", 0))
        days_left = row["days_of_stock_left"]
        items.append(ItemForecast(
            store_id=str(row["Store ID"]),
            product_id=str(row["Product ID"]),
            category=row.get("Category"),
            region=row.get("Region"),
            inventory_level=float(row["Inventory Level"]),
            forecasted_daily_demand=round(float(row["Predicted_Demand"]), 2),
            days_of_stock_left=float(days_left) if np.isfinite(days_left) else 999.0,
            reorder_point_units=round(float(row["reorder_point_units"]), 2),
            recommended_order_qty=int(row["recommended_order_qty"]),
            alert_level=row["alert_level"],
            trend=trend_dir,
        ))
    return items


# -----------------------------------------------------------------------
# ENDPOINTS
# -----------------------------------------------------------------------
@app.get("/health", tags=["System"])
def health_check():
    """Basic liveness check -- confirms the API is up and the model artifacts loaded."""
    try:
        get_model()
        model_ready = True
    except Exception as e:
        model_ready = False
    return {"status": "ok" if model_ready else "degraded", "model_loaded": model_ready}


@app.get("/schema", response_model=SchemaResponse, tags=["System"])
def get_required_schema():
    """Returns the required CSV/JSON columns, so client apps (e.g. the website's
    upload form) can validate data before sending it."""
    return SchemaResponse(
        required_columns=REQUIRED_COLUMNS,
        example_row=SalesRecord.Config.json_schema_extra["example"],
    )


@app.get("/model/info", response_model=ModelInfo, tags=["System"])
def model_info(client: str = Depends(require_api_key)):
    """Model accuracy metrics and top feature importances, for an internal
    monitoring/admin dashboard."""
    logger.info(f"/model/info called by client '{client}'")
    metrics = get_metrics()
    return ModelInfo(
        mae=metrics.get("mae"),
        rmse=metrics.get("rmse"),
        mape=metrics.get("mape"),
        r2=metrics.get("r2"),
        top_features=get_feature_importance(),
    )


@app.post("/forecast", response_model=ForecastResponse, tags=["Forecasting"])
async def forecast_from_csv(
    file: UploadFile = File(..., description="CSV file matching the required schema (see /schema)"),
    lead_time_days: int = Query(7, ge=1, le=60),
    safety_stock_days: int = Query(3, ge=0, le=30),
    critical_days_threshold: float = Query(3, ge=0),
    warning_days_threshold: float = Query(7, ge=0),
    client: str = Depends(require_api_key),
):
    """
    Upload a CSV of sales/inventory data and receive a forecast + restock alert
    for every store-item combination in the file.

    This is the primary endpoint for the website integration: the frontend
    uploads a store's exported sales CSV and gets back a ranked restock list.
    """
    logger.info(f"/forecast called by client '{client}', file='{file.filename}'")

    if not file.filename.lower().endswith(".csv"):
        raise HTTPException(status_code=400, detail="File must be a .csv")

    try:
        contents = await file.read()
        raw_df = pd.read_csv(io.BytesIO(contents))
        raw_df.columns = [c.strip() for c in raw_df.columns]
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Could not parse CSV: {e}")

    missing_cols = [c for c in REQUIRED_COLUMNS if c not in raw_df.columns]
    if missing_cols:
        raise HTTPException(
            status_code=422,
            detail=f"Missing required columns: {missing_cols}. See /schema for the full list.",
        )

    try:
        result = run_full_pipeline(raw_df)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Forecasting failed: {e}")

    latest = (
        result.sort_values(DATE_COL)
        .groupby(GROUP_COLS, as_index=False)
        .last()
    )
    alerts = generate_alerts(
        latest,
        lead_time_days=lead_time_days,
        safety_stock_days=safety_stock_days,
        critical_days_threshold=critical_days_threshold,
        warning_days_threshold=warning_days_threshold,
    )

    items = build_item_forecasts(alerts)
    return ForecastResponse(
        n_items=len(items),
        n_critical=sum(1 for i in items if i.alert_level == "Critical"),
        n_warning=sum(1 for i in items if i.alert_level == "Warning"),
        n_ok=sum(1 for i in items if i.alert_level == "OK"),
        n_overstock=sum(1 for i in items if i.alert_level == "Overstock"),
        items=items,
    )


@app.post("/forecast/records", response_model=ForecastResponse, tags=["Forecasting"])
async def forecast_from_records(payload: ForecastRecordsRequest, client: str = Depends(require_api_key)):
    """
    JSON alternative to /forecast, for when the website already holds the data
    in its own database and wants to send it directly without a CSV round-trip.

    Request body shape:
        {
          "records": [ {..SalesRecord fields..}, ... ],
          "settings": { "lead_time_days": 7, "safety_stock_days": 3, ... }   # optional
        }
    """
    logger.info(f"/forecast/records called by client '{client}', n_records={len(payload.records)}")
    records = payload.records
    settings = payload.settings
    if not records:
        raise HTTPException(status_code=400, detail="No records provided")

    raw_df = pd.DataFrame([r.dict(by_alias=True) for r in records])

    try:
        result = run_full_pipeline(raw_df)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Forecasting failed: {e}")

    latest = (
        result.sort_values(DATE_COL)
        .groupby(GROUP_COLS, as_index=False)
        .last()
    )
    alerts = generate_alerts(
        latest,
        lead_time_days=settings.lead_time_days,
        safety_stock_days=settings.safety_stock_days,
        critical_days_threshold=settings.critical_days_threshold,
        warning_days_threshold=settings.warning_days_threshold,
    )

    items = build_item_forecasts(alerts)
    return ForecastResponse(
        n_items=len(items),
        n_critical=sum(1 for i in items if i.alert_level == "Critical"),
        n_warning=sum(1 for i in items if i.alert_level == "Warning"),
        n_ok=sum(1 for i in items if i.alert_level == "OK"),
        n_overstock=sum(1 for i in items if i.alert_level == "Overstock"),
        items=items,
    )


@app.get("/", tags=["System"])
def root():
    return {
        "name": "Store Stock Assistant API",
        "docs": "/docs",
        "health": "/health",
        "endpoints": ["/forecast (POST, CSV upload)", "/forecast/records (POST, JSON)", "/schema", "/model/info"],
    }
